version: "3.7"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres_password

    volumes:
      - ./umar-db:/var/lib/postgresql/data

  node_api:
    container_name: restapi
    build:
      context: "./app"

    depends_on:
      - postgres
    ports:
      - "8081:8081"

volumes:
  umar-db:
